### PR TITLE
css-canvas-medical | Eniola Johnson

### PR DESCRIPTION
**Pull request by eniolajohnson**
image
image
image

### CODE REVIEW

**Comment by eniolajohnson** [comment]
I changed an id css selector to a class selector and renamed it into something more appropriate.

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Its looking excellent! Here is some feedback: 

For the Nav: 
	Contact Us button should be a little smaller
For the image: 
	image should be a little lighter, try the `filter` CSS property
	image width should be reduced 
For the clinician section:
	there should be more space between the lines of text
Ready to learn section:
	Button and text should be closer together
Footer:
	Should be less space between the CANVAS heading and the address text
Bottom links:
	looks good

**Comment by eniolajohnson** [comment]
Implemented feedback
image
image
image

**Review by Zhiwutian — APPROVED** [review]
👍

**Pull request merged**
